/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Full API - Users, Sessions, Tasks
 * API for managing users, sessions, tasks
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from './api-instance';
import type { BodyType } from './api-instance';
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  admin: 'admin',
  editor: 'editor',
  viewer: 'viewer',
} as const;

export interface User {
  id: string;
  email: string;
  role: UserRole;
  name: string;
  avatarId?: string;
}

export interface CreateUser {
  id: string;
  email: string;
  password: string;
  role: UserRole;
  name: string;
  avatarId?: string;
}

export interface SignIn {
  email: string;
  password: string;
}

export interface Session {
  id: string;
  name: string;
  avatarId?: string;
  userId: string;
  email: string;
  role: UserRole;
}

export type SuccessResponseData = { [key: string]: unknown };

export type SuccessResponse = {
  data?: SuccessResponseData;
  /** @nullable */
  error?: string | null;
  success?: boolean;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves information about the current session, including user details and session ID.

 * @summary Get current session
 */
export const getSession = (options?: SecondParameter<typeof createInstance>) => {
  return createInstance<Session>({ url: `/session/me`, method: 'GET' }, options);
};

/**
 * Authenticates the user and returns session details.

 * @summary Sign in
 */
export const signIn = (signIn: BodyType<SignIn>, options?: SecondParameter<typeof createInstance>) => {
  return createInstance<Session>(
    { url: `/session/sign-in`, method: 'POST', headers: { 'Content-Type': 'application/json' }, data: signIn },
    options
  );
};

/**
 * Ends the current session for the authenticated user.

 * @summary Sign out
 */
export const signOut = (options?: SecondParameter<typeof createInstance>) => {
  return createInstance<null>({ url: `/session/sign-out`, method: 'POST' }, options);
};

export type GetSessionResult = NonNullable<Awaited<ReturnType<typeof getSession>>>;
export type SignInResult = NonNullable<Awaited<ReturnType<typeof signIn>>>;
export type SignOutResult = NonNullable<Awaited<ReturnType<typeof signOut>>>;
